trigger:
- main  # Cambia 'main' si el nombre de tu rama principal es diferente.

pool:
  name: PhotoPost  # Usa el nombre de tu agent pool.

steps:
# 1. Cambiar al directorio del proyecto
- script: cd $(Build.SourcesDirectory)
  displayName: "Navegar al directorio del proyecto"

# 2. Instalar dependencias de Flutter
- script: |
    cd $(Build.SourcesDirectory)
    flutter pub get
  displayName: "Instalar dependencias"

# 3. Ejecutar pruebas
- script: |
    cd $(Build.SourcesDirectory)
    flutter test
  displayName: "Ejecutar pruebas"

# 4. Construir el APK en modo release
- script: |
    cd $(Build.SourcesDirectory)
    flutter build apk --release
  displayName: "Construir APK"

# 5. Publicar el APK como artefacto
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)/build/app/outputs/flutter-apk/app-release.apk'
    artifactName: 'FlutterAPK'
    publishLocation: 'Container'
